---
# This role installs NodeJS via NVM (Node Version Manager)
# Ref: https://github.com/creationix/nvm.git

- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
    creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ nvm.node_version }} && nvm alias default {{ nvm.node_version }}"
    creates=/home/{{ ansible_user_id }}/.nvm/alias
