---
# This role installs NodeJS via NVM (Node Version Manager)
# Ref: https://github.com/creationix/nvm.git

- name: Install nvm
  become: yes
  become_user: "{{ nvm.user }}"
  git:
    repo: https://github.com/creationix/nvm.git
    dest: ~/.nvm
    version: "{{ nvm.version }}"
  tags: nvm

- name: Source nvm in ~/.zshrc and/or ~/.bashrc
  become: yes
  become_user: "{{ nvm.user }}"
  blockinfile:
    path: "{{ item }}"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
  with_items:
    - ~/.zshrc
    - ~/.bashrc
  tags: nvm

- name: Install {{ nvm.node_version }}
  script: files/install_node.sh {{ nvm.node_version }}
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stdout"
  tags: nvm
