---
# This role installs NodeJS via NVM (Node Version Manager)
# Ref: https://github.com/creationix/nvm.git

- name: Install NVM using Git
  git:
    repo: 'https://github.com/creationix/nvm.git'
    dest: /home/{{ ansible_user }}/.nvm
    version: '{{ nvm_version }}'

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ nvm_node_version }} && nvm alias default {{ nvm_node_version }}"
    creates=/home/{{ nvm_user }}/.nvm/alias
