---
- name: Custom shell login splash
  copy:
    src: motd
    dest: /etc/motd

- name: Other software we want
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - git
    - wget
    - curl
    - zsh
    - htop
    - tmux
    - tree
    - emacs

