---
# This playbook provisions a DevBox for a specific purpose

- hosts: all

  roles:
    # Project stuff
    - java
    - maven
    - nvm
    - chrome
    - vscode
    - svn
    # Project DevBox niceties
    - lxde-settings
    # User-specific stuff
    - neovim
    - zsh
