---
# This playbook provisions a DevBox for a specific purpose

- hosts: all

  roles:
    # User-specific stuff
    - neovim
    - zsh
    # Project stuff
    - java
    - maven
    - nvm
    - chrome
    - vscode
    - svn
    # DevBox niceties
    - lxde-settings

  vars:
    nvm_node_version: '6.11.3'
